spring:
  application:
    name: Travel-Insurance

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/travelInsurance?autoReconnect=true&createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
medcoanalytics:
  app:
    jwtSecret: ${JWT_SECRET:abcdefghijKLMNOPQRSTUvwxyz=====provider====0123456987}
    jwtExpirationMs: 86400000

logging:
  level:
    org.hibernate: DEBUG
    org.springframework.transaction: TRACE

file:
  dir-attachments: ${FILE_ATTACHMENTS_DIR:C:/Users/pc/Pictures/travelFile}

servlet:
  multipart:
    enabled: true
    max-file-size: 100MB
    max-request-size: 120MB
    file-size-threshold: 2MB
    resolve-lazily: true

server:
  port: 8900

# MAPFRE API Configuration
mapfre:
  api:
    key: ${MAPFRE_API_KEY:dev-mapfre-api-key}
    url: ${MAPFRE_API_URL:http://localhost:8900/mock/mapfre}

# chapa API Configuration
chapa:
  api:
    base-url: ${CHAPA_BASE_URL:https://api.chapa.co/v1/transaction/initialize}
    key: ${CHAPA_API_KEY:}
    callback-url: ${CHAPA_CALLBACK_URL:http://localhost:8900/api/travel/payments/callback}
    return-url: ${CHAPA_RETURN_URL:http://localhost:5173/pdf}
    verify-url: ${CHAPA_VERIFY_URL:https://api.chapa.co/v1/transaction/verify}

afromessage:
  api:
    url: ${AFROMESSAGE_API_URL:https://api.afromessage.com/api/send}
    token: ${AFROMESSAGE_TOKEN:}
    identifierId: ${AFROMESSAGE_IDENTIFIER_ID:}
#    senderName:
#    callbackUrl: http://192.168.100.82:8888/api/notifications/sms-status

openai:
  api:
    key: ${OPENAI_API_KEY:}
    url: ${OPENAI_API_URL:https://api.openai.com/v1/chat/completions}
  model: gpt-3.5-turbo