spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/travelInsurance?autoReconnect=true&createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.transaction: TRACE

server:
  port: ${SERVER_PORT:8900}

# Add development-specific JWT secret
medcoanalytics:
  app:
    jwtSecret: ${JWT_SECRET:abcdefghijKLMNOPQRSTUvwxyz=====provider====0123456987}  # Safe for development