spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

logging:
  level:
    root: INFO
    org.hibernate: WARN
    org.springframework.transaction: WARN

server:
  port: ${SERVER_PORT:8900}

# Add these to your prod configuration
medcoanalytics:
  app:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: 86400000

# Add other production-specific configs
mapfre:
  api:
    key: ${MAPFRE_API_KEY}
    url: ${MAPFRE_API_URL}

chapa:
  api:
    key: ${CHAPA_API_KEY}
    base-url: ${CHAPA_BASE_URL}
    callback-url: ${CHAPA_CALLBACK_URL}

afromessage:
  api:
    token: ${AFROMESSAGE_TOKEN}
    identifierId: ${AFROMESSAGE_IDENTIFIER_ID}

openai:
  api:
    key: ${OPENAI_API_KEY}