spring:
  application:
    name: Travel-Insurance

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/travelInsurance?autoReconnect=true&createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
medcoanalytics:
  app:
    jwtSecret: "aVZyeWVkT0tFQmlGVEl3QVBwWmJpTGhoNnpncWZjeWg="
    jwtExpirationMs: 86400000

logging:
  level:
    org.hibernate: DEBUG
    org.springframework.transaction: TRACE

file:
  dir-attachments: C:/Users/pc/Pictures/travelFile

servlet:
  multipart:
    enabled: true
    max-file-size: 100MB
    max-request-size: 120MB
    file-size-threshold: 2MB
    resolve-lazily: true

server:
  port: 8900

# MAPFRE API Configuration
mapfre:
  api:
    key: dev-mapfre-api-key
    url: http://localhost:8900/mock/mapfre

# chapa API Configuration
chapa:
  api:
    base-url: https://api.chapa.co/v1/transaction/initialize
    key: CHASECK_TEST-n4BnVZS3FuFT6gVcqy3CN5rB2DhtGMzn

afromessage:
  api:
    url: "https://api.afromessage.com/api/send"
    token: eyJhbGciOiJIUzI1NiJ9.eyJpZGVudGlmaWVyIjoiYkpUZ1VZVzJoaTZnaFo5QTJDSjBaU3pzeWhLZ2ZtVWsiLCJleHAiOjE4OTM0NzkxNjUsImlhdCI6MTczNTcxMjc2NSwianRpIjoiMmVlMGNmOWUtOGFlMC00NDQ0LWFjY2UtODdhNjU0MjhiNmQxIn0.D5_eQNtA4HNaNuVo1O6pydwaZ-sn3fpWZa-g4rjl1IU
    identifierId: e80ad9d8-adf3-463f-80f4-7c4b39f7f164
#    senderName:
#    callbackUrl: http://192.168.100.82:8888/api/notifications/sms-status

openai:
  api:
    key: "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"
    url: https://api.openai.com/v1/chat/completions
  model: gpt-3.5-turbo