spring:
  application:
    name: Travel-Insurance

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/travelInsurance?autoReconnect=true&createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
medcoanalytics:
  app:
    jwtSecret: "aVZyeWVkT0tFQmlGVEl3QVBwWmJpTGhoNnpncWZjeWg="
    jwtExpirationMs: 86400000

logging:
  level:
    org.hibernate: DEBUG
    org.springframework.transaction: TRACE

file:
  dir-attachments: C:/Users/pc/Pictures/travelFile

servlet:
  multipart:
    enabled: true
    max-file-size: 100MB
    max-request-size: 120MB
    file-size-threshold: 2MB
    resolve-lazily: true

server:
  port: 8888

# MAPFRE API Configuration
mapfre:
  api:
    key: dev-mapfre-api-key
    url: http://localhost:8080/mock-mapfre/calculate-premium


# Telebirr API Configuration
telebirr:
  api:
    key: your_api_key_here
    url: https://api.telebirr.com

afromessage:
  api:
    url: "https://api.afromessage.com/api/send"
    token: "eyJhbGciOiJIUzI1NiJ9.eyJpZGVudGlmaWVyIjoiVzlRRkRLSGxMbVhxcjRCM3Z5bUI3MEdiVUZudjFGVHQiLCJleHAiOjE4ODc2Mjg3NDksImlhdCI6MTcyOTg2MjM0OSwianRpIjoiNTYzYWEyNWYtNzExNi00N2YzLTg3ZjctOTBiNmYxMWE0NjcwIn0.7iqjiLxmvLfkN50NlRAGTeDpa0TvGynB_X7Q93PdDnA"
    identifierId: "e80ad9d8-adf3-463f-80f4-7c4b39f7f164"
    senderName: MEDCO
    callbackUrl: http://192.168.100.82:8888/api/notifications/sms-status